language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
     env: TOXENV=py37

before_install:
  - python -m pip install -U pip
install:
  - python -m pip install codecov pre-commit tox
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pre-commit run --all-files; fi
  - tox
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coverage xml; codecov; fi

